tidyverse/lubridate

R/intervals.r, R/ops-%m+%.r, inst/tests/test-rollback.R, inst/tests/test-timespans.R
With previous version, we had:
```r
> naiss <- ymd_hms("1992-02-29 12:00:00")
> evt <- ymd_hms("2014-03-01 01:00:00")
> time_length(interval(naiss, evt), "years")
[1] 21.99874
```
We should consider that the anniversary occurs between 28 Feb at 23:59:59 and 1st March at 00:00:00. Therefore, `%m++%` should rollback at 00:00:00. In that case:
```r
> time_length(interval(naiss, evt), "years")
[1] 22.00011
```
=> Improving time_length for 29 Feb (when dealing with date time)

NEWS, R/parse.r, inst/tests/test-parsers.R
With as.character(), long numbers get converted to scientific
notation which the parse of course fails to recognise. Using
format(..., scientific = FALSE) prevents that.
=> Allow to parse dates from long numbers

R/round.r, inst/tests/test-round.R, man/ceiling_date.Rd, man/floor_date.Rd, man/round_date.Rd
In reference to [Issue 239](https://github.com/hadley/lubridate/issues/239).
=> Adding "quarter" option to floor/ceiling_date

R/instants.r
I think there is just a typo here, because right now you get an error from `origin + milliseconds(1)`
=> origin should be a POSIXct class and inherit from POSIXt

DESCRIPTION
src/tparse.c specifies GPL-2 but the DESCRIPTION file just says GPL.  This patch fixes it.
=> Specify GPL version from src/tparse.c

R/round.r
Title of documentation was "Round, flour and ceiling methods for date-time objects." Because no baking is involved, I assumed "flour" should be "floor".
=> Corrected minor typo in title of round.r

R/periods.r
```
> period(second = 0.02)  
[1] "2S"
```
The regex omitted the decimal place
=> Fix period format

NEWS.md, R/round.r, man/round_date.Rd, tests/testthat/test-round.R
For #268. Did a little refactoring to re-use the formula used in rounding to "quarter".
Also, deleted that `parse_unit_spec` function since it really was dead code, and changed an errant tab to spaces.
Still need to write specs.
=> Add "bimonth" and "halfyear" options to round_date and friends

R/durations.r, tests/testthat/test-durations.R
Previously format(duration(75.25)), for example, would fail because .read_duration used %d as the format specifier in sprintf. In order to match the existing format.Duration tests, I simply round the seconds.
Added tests to test-durations.R
=> Fix format.Duration for durations greater than a minute with fractional seconds

R/accessors-quarter.r, man/quarter.Rd, tests/testthat/test-accessors.R
This is a follow-up to Pull Request #427 , but I couldn't figure out how to use git properly to bring my old fork up so I deleted and started again. 
I removed shift as requested, and created a fiscal_start parameter instead. Specifying a month other than 1 for the start of the fiscal year will shift the quarter (and the year if needed). For example, setting 11 for start will mean that Nov, Dec, Jan are all Q1. For Nov and Dec, the year will increment by 1 if with_year = TRUE. That is, 2013-11 will show as 2014.1 (1st quarter of 2014, as is convention when using fiscal quarters). 
I have also added tests for quarters which did not exist previously.
=> add fiscal_start to quarter when fiscal year doesn't begin in january

NEWS.md, R/round.r, tests/testthat/test-round.R
Proposition to fix #486 . 
I added some tests and News bullet point
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hadley/lubridate/488)
=> ceiling_date handles missing value propely

NEWS.md, R/accessors-month.r, man/month.Rd, tests/testthat/test-accessors.R
Return localized month in the same way as weekday.
=> [Fix #401 ext] Return localized labels in month

NEWS.md, R/coercion.r
See discussion of this bug here:
http://stackoverflow.com/questions/42563471/unexpected-value-in-lubridate-as-numeric-using-value-months-in-units-arg/
=> [Fix #490] Correctly compute length of period in months

man/ymd.Rd
Just noticed this in the documentation - `evalueates` should read `evaluates`.
Hope this is helpful.
=> Very, very minor typo correction

R/parse.r
This is the second pull request for this problem, now modifying the roxygen documentation instead of the resulting Rd file.
Sorry for the trouble...
=> Fix a typo in hms documentation

NEWS.md, R/round.r
Changed `y <- as.POSIXlt(x)` to `x <- as.POSIXlt(x)` to reduced the memory footprint of `trunc_multi_unit` and overwrite `x` rather than creating a new vector `y`.  Not a large change, but can be useful when `x` is a very long vector (currently using 1b records).
=> trunc_multi_unit 

R/zzz.R
Hi, 
the fix a55725c1 for #575 has a small error that prevent the installation of lubridate. 
```r
Error: package or namespace load failed for 'lubridate':
.onAttach failed in attachNamespace() for 'lubridate', details:
call: Sys.setenv("TZDIR", tzdir)
error: all arguments must be named
Erreur : le chargement a échoué
```
this PR changes this.
=> Correctly sets TZDIR env (#575)

R/round.r
In `round_ceiling` when rounding to month, there is a partial match of `month` to `months` in the `update` call: 
``` r
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date
options(warnPartialMatchArgs = TRUE)
x <- as.POSIXct(c("2009-08-03 12:01:59.23", "2010-08-03 12:01:59.23"), tz = "UTC")
ceiling_date(x, "month")
#> Warning in (function (object, years = integer(), months = integer(), days =
#> integer(), : partial argument match of 'month' to 'months'
#> [1] "2009-09-01 UTC" "2010-09-01 UTC"
```
=> Avoid partial match warning on update in round_ceiling when rounding to month

R/parse.r
Fixed text for the select_formats argument: Se -> See; tockens -> tokens; it -> It
=> Fixed typo's in parse.r: select_formats argument

src/update.cpp
The result of `get_system_tz` comes from a `STRING_ELT`, which seems to be automatically garbage collected, causing the static character pointer to point to an invalid location. Duplicating the string is a small leak, but prevents this invalid access.
Alternatively, you could not do the memoization; I'm not sure what the benefit or downside of that is.
This should fix several of the [failures on CRAN](https://cran.r-project.org/web/checks/check_results_lubridate.html).
=> Fix system timezone memoization.

src/update.cpp
Nothing from it is used, plus it's an "internal" cctz file so dropping
the include allows building against an unbundled system cctz.
=> Remove extraneous include.

R/coercion.r
Quick fix in documentation source for #660
=> Fix #660 typo in as.period examples: units --> unit

R/parse.r
Should POSIXct values like '2012-06-01 12:23' be considered a date-time, not a date?
=> "date-time", not "date"

README.Rmd, README.md
As discussed in https://github.com/tidyverse/lubridate/issues/641, @hadley asked me to add thumbnails for tidyverse packages with cheat sheets to their READMEs.
The thumbnail image is hosted through the rstudio/cheatsheets repo, as not to add to the size of the package itself.
=> Add lubridate cheat sheet thumbnail to README.

R/package.r, man/lubridate-package.Rd
1. Drop parenthesis for `origin` as `origin` is an object, not a function.
2. Add "`" around a piece of code.
3. Add a missing period.
=> Fix typoes

DESCRIPTION
The DESCRIPTION file contains two unneeded commas in `Imports` and `LinkingTo`.
=> Remove unneeded commas from DESCRIPTION file

NEWS.md, R/durations.r, man/hidden_aliases.Rd, tests/testthat/test-durations.R, tests/testthat/test-ops-compare.R
Closes #695. 
Let me know if you prefer to have the coercion go the other way, ie: 
```
setMethod("Compare", signature(e1 = "Duration", e2 = "numeric"),
function(e1, e2) {
callGeneric(as.numeric(e1, "secs"), e2)
})
```
Also will fix tidyverse/ggplot2#2414
=> Add Compare method for duration and numeric objects.

R/guess.r, R/parse.r, man/guess_formats.Rd, man/hms.Rd, man/parse_date_time.Rd, man/ymd.Rd, man/ymd_hms.Rd
I made some minor updates to the documentation for the date/time parsing functions. I fixed a few typos and improved the formatting in certain places.
=> Update docs for parsing dates and times

R/periods.r
I noticed a repeated section in the docs for period. Here's a PR to fix it.
=> Fix typo in period docs

R/accessors-week.r, R/accessors-year.r
Previous epi week link was not resolving to an existing page.
The best replacement on the CMMCP website would probably be [this one](https://www.cmmcp.org/mosquito-surveillance-data/pages/epi-week-calendars-2008-2019), but we might as well cite the original paper referenced.
Just in case, I also archived the PDF on the Internet Archive's Wayback Machine: https://web.archive.org/web/20190724124018/https://www.cmmcp.org/sites/cmmcp/files/uploads/spring_skeeter_06.pdf
=>  replace dead link by document cited, use https

R/ops-addition.r
This is a small (but noticeable!) optimization to `add_months()`, and through it, the common case of `<date> + days()`.
```r
library(lubridate, warn.conflicts = FALSE)
x <- as.Date("2019-01-01") + 0:100000
bench::mark(x + days(1), iterations = 100)
#> # A tibble: 1 x 6
#>   expression       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 x + days(1)    149ms    153ms      6.42      33MB     76.5
bench::mark(x + days(1), iterations = 100)
#> # A tibble: 1 x 6
#>   expression       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 x + days(1)    109ms    113ms      8.74    23.8MB     28.5
```
=> In `add_months()`, conditionally attempt to add months

R/parse.r
I was briefly confused when  `d` was presented in the `parse_date_time()` docs as `d!`, and wondered whether there had been a UI change where this `!` was meaningful. My change visually separates these markers from the date-time format tag so that it is clearer that they are not part of the tag itself.
=> Separate *! markers from date-time formats

.Rbuildignore, .github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml, .github/workflows/pr-commands.yaml, README.Rmd, README.md
These workflows were added with:
```R
usethis::use_github_actions_tidy()
usethis::use_github_action("pkgdown.yaml")
```
After copying the badge output from `use_github_actions_tidy` to `README.Rmd`,
rebuilt `README.md` with `devtools::build_readme()`.
Install of `tidytemplate` is ported from the `.travis.yml`.
Fixes #851.
=> Setup GitHub actions workflows for R-CMD-check, pkgdown & pr-commands

R/round.r, man/round_date.Rd
fixes #850 
- there are no examples printing out datasets 
- mtcars isn't used at all
=> refresh round_date() docs

R/coercion.r, man/as_date.Rd
Fixed #839
The original request was tackling 2 problems
- There was no mention in the documentation of  NA generation by `as_date` and `as_datetime`
- Generate a warning for `make_date` and `make_datetime`, but I found the 2 functions were not consistent how they handle out of range value (see #855) => not implemented in this pull request
=> Update documentation as-date

DESCRIPTION
These packages are not used anywhere in lubridate, so I think it makes sense to drop them.
Fixes #821
=> Strip enhances

src/datetime.c, src/utils.c, src/utils.h
This function actually checks if the day number is valid in a given month, so it's better named `check_mdays`. Also, there is one unused argument, which I've removed.
=> rename check_ymd to check_mdays; remove unused argument

src/cctz/src/time_zone_libc.cc
Port of 98fb541 from upstream cctz to fix builds on AIX, see
https://github.com/google/cctz/pull/177
=> Fix tm_gmtoff build failure on AIX

R/zzz.R
This commit fixes https://github.com/tidyverse/lubridate/issues/928 for me. 
I start R --vanilla and then:
```
❯ R --vanilla
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Platform: x86_64-apple-darwin19.6.0 (64-bit)
r$> Sys.getenv("TZDIR")
[1] ""
r$> lubridate::dmy_hm("1 Sep 2020 1:00pm", tz="Africa/Blantyre")
[1] "2020-09-01 13:00:00 CAT"
r$> Sys.getenv("TZDIR")
[1] "/usr/share/zoneinfo"
```
<details><summary>session_info</summary>
<p>
```
r$> devtools::session_info()
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
setting  value
version  R version 4.0.3 (2020-10-10)
os       macOS Catalina 10.15.7
system   x86_64, …
```
=> [#928] Set TZDIR if empty

R/parse.r
This is very minor, but is a small proposed change to the wording for `cutoff_2000`
The 19th/20th centuries mentioned in the current comment feels misleading. Technically (and we all <3 being technical) the 21st century started 1st Jan 2001 - see https://en.wikipedia.org/wiki/21st_century 
To avoid confusion/misinterpretation I've changed this to simply talk about "starting with `19`" and "starting with `20`"
=> Documentation: 19th and 20th century ambiguity

NEWS.md, R/accessors-quarter.r, man/parse_date_time.Rd, man/quarter.Rd, tests/testthat/test-accessors.R
Addresses https://github.com/tidyverse/lubridate/issues/947. With this, the API now looks like:
```r
quarter(x) # default behaviour is unchanged
quarter(x, type = "quarter_year") # equivalent to what would previously be passing `with_year = TRUE`
quarter(x, type = "date_first") # new functionality
quarter(x, type = "date_last") # new functionality
```
The `with_year` parameter is soft-deprecated, but will continue to work for the time being.
=> Refactors `quarter()` API to allow for quarter start- and end-dates

R/stamp.r
Pass `quiet` parameter to `stamp`.
So that parameters of `stamp_date` and `stamp_time` are more consistent with `stamp` itself.
(and allow reduction of unwanted 'informative' messages).
example:
```
> dateformat <- lubridate::stamp_date("2021-07-15")
Multiple formats matched: "%Y-%Om-%d"(1), "%Y-%m-%d"(1)
Using: "%Y-%Om-%d"
> dateformat <- lubridate::stamp_date("2021-07-15", quiet = TRUE)
> dateformat
function(x, locale = .(locale)) {
.(reset_local_expr)
format(x, format = .(FMT))
}
<environment: 0x55ab54c3efb0>
> timeformat <- lubridate::stamp_time("4:53 p.m.", quiet = TRUE)
Warning message:
hms, hm and ms usage is deprecated, please use HMS, HM or MS instead. Deprecated in version '1.5.6'. 
> timeformat(Sys.time())
[1] "18:38 p.m."
> timeformat <- lubridate::stamp_time("4:53 p.m.") …
```
=> `quiet` parameter for `stamp_date` and `stamp_time`

R/guess.r, tests/testthat/test-guess.R
Raising a small issue with `guess_formats()` along with a proposed easy fix.
Documentation of `guess_formats()` indicated that b & B are considered equivalent.  This is true in the actual parser called by `.strptime`, but not in the guessing code.  Previously, this could lead to parsing failure when "B" was used alongside data that only contained abbreviated months.  
A simple change in string substitution in the function appears to correct things issue.  Given the if-statement on the line just above the one edited, I think this is just fixing a typo to match what was already intended.
**Currently:**
``` r
require(lubridate, quietly = TRUE, warn.conflicts = FALSE)
mixed <- c("jan 3 2010", "January 5 1999")
abbrev <- c("jan 3 2010", "Jan 1, 1999")
guess_formats(mixed, c("BdY"), …
```
=> Both B and b now call C parser 0b in guess_formats()

R/durations.r
Closes #988 
I fixed 1 typo in documentation and 1 style error in the code (see commits)
=> Fix parsing and style of examples in `durations.r`

NEWS.md, R/durations.r, R/ops-subtraction.r, R/periods.r, man/hidden_aliases.Rd
Closes #994 
This PR adds two `-` S4 methods to disambiguate the case where you subtract two Period or two Duration objects.
This is hard to test because the Note appears once per session, but I've added a comment to try and keep us from accidentally removing this in the future.
=> Disambiguate `<Duration> - <Duration>` and `<Period> - <Period>`

R/intervals.r, man/duration.Rd, man/round_date.Rd, man/within-interval.Rd
It seems like some of the Rd files have gotten out of date, so I just ran `devtools::document()` to update.
Also fixed a CRAN check note about a long line in one of the files that got updated:
```r
> checking Rd line widths ... NOTE
Rd file 'within-interval.Rd':
\examples lines wider than 100 characters:
These lines will be truncated in the PDF manual.
```
=> Re-document package

R/coercion.r, R/format_ISO8601.r
Use  format()  not as.character()   for  POSIX[cl]t  and Date   --- will pass CRAN checks with R-devel
=> Fix R-devel CRAN checks: use format(), not as.character() for time/date

NEWS.md, R/parse.r, tests/testthat/test-parsers.R
=> Recycle the `isdst` field in `.mklt()`

DESCRIPTION, NEWS.md, R/accessors-day.r, R/cyclic_encoding.r, R/round.r, R/update.r, man/DateTimeUpdate.Rd, man/cyclic_encoding.Rd, man/day.Rd, man/round_date.Rd, tests/testthat/test-round.R
Closes #1017
Initial work; filing here to get high-level agreement before finishing tests & all. Also wasn't having any luck fidgeting with `LC_TIME` to try and get non-English week names to show up so we can test that too, any ideas?
=> initial work setting week_start by string

DESCRIPTION, NEWS.md, R/vctrs.R, R/zzz.R, tests/testthat/test-vctrs.R
Closes #1072 
We now store the names on the column that corresponds to the `@.Data` slot of the original object. For Period this is `$second` and for Interval this is `$span`. This fixes the problem of #1072 because it means that we never have a mismatch in the number of columns that are on the proxy.
A few extra niceties here:
- No need for compare/equal proxy methods anymore, we just carry around the names unconditionally, which doesn't hurt anything
- No need for the complicated recursive proxying done in the Interval methods, because in vctrs 0.5.0 if a data frame is returned as the proxy then it will automatically proxy the columns recursively too (CC @lionel- this is a nice side effect of that change we made)
=> Place names on the `.Data` column of the proxy

NEWS.md, R/coercion.r, tests/testthat/test-periods.R
=> Fix `@year` slot recycling in `as.period(unit = "month")`

DESCRIPTION, R/periods.r, man/period.Rd
Given the context, `period()` seems appropriate, not `duration()`.
=> docs: use period() in period's examples

R/accessors-quarter.r, man/quarter.Rd
=> Fix typo in `quarter()` documentation

R/tzdir.R
As discussed in #1117, this allows lubridate to use the timezone database in a conda environment if R is currently being executed in one. The conda environment is detected and located using the `CONDA_PREFIX` environment variable.
The behavior of lubridate was tested before and after this change. Indeed, the timezone information that is installed by the standard `tzdata` conda package at `${CONDA_PREFIX}/share/zoneinfo` is detected and used.
Please check the logic around the handling of Windows. Because conda environment can exist on Windows (and are actually a very nice way to set up a scientific programming environment there), I reorganized the way `tzdir_find` works to avoid too much nesting.
=> Use CONDA_PREFIX for timezone database if available

DESCRIPTION
Alternatively, since the newer version is really only required in tests, we can `skip_if_not_installed("timechange, "0.2.0")` here:
https://github.com/tidyverse/lubridate/blob/e54b612c0672c57bb9cea12dd2482b0d59b3aa64/tests/testthat/test-round.R#L655
=> timechange dependency is 0.2.0

README.Rmd, README.md, _pkgdown.yml
Noticed that the lubridate REAMDE & pkgdown points to https://r4ds.had.co.nz/dates-and-times.html, which itself then points to https://r4ds.hadley.nz/datetimes.html. I've gone in and changed both to just go straight to https://r4ds.hadley.nz/datetimes.html, and re-rendered the README, to save someone a job.
=> Use R for Data Science 2nd Edition

R/leap-years.r, src/init.c, src/utils.c, tests/testthat/test-utilities.R
I noticed the [fastymd](https://cran.r-project.org/package=fastymd) package hitting CRAN recently. One of its features is fast leap year calculations, which made me wonder how lubridate stacks up.
Currently `leap_year()` is pure R and is relatively speaking quite slow. With the lubridate main branch:
``` r
library(microbenchmark)
set.seed(42)
years <- sample(4000, 1e4, replace = TRUE)
microbenchmark(
fastymd::is_leap(years),
lubridate::leap_year(years),
times = 1e4
)
#> Unit: microseconds
#>                         expr   min    lq       mean median     uq      max neval cld
#>      fastymd::is_leap(years)  29.4  47.8   65.64309   52.6   64.2  11538.7 10000  a 
#>  lubridate::leap_year(years) 792.3 986.5 1203.30433 1020.2 1139.0 298644.7 10000   b
```
<sup>Created on 2025-05-01 with …
=> Implement `leap_year()` in C
