tidyverse/lubridate

R/help.r
R/periods.r
vignettes/lubridate.Rmd

This commit makes small changes to the documentation for lubridate. …
- Fix spacing typo.
- Add hours() link in docs for consistency
- Fix knitr close bracket in vignette

Small edits to docs.

---

NEWS.md

This solves the Rmd/knitr rendering problems at my end; hopefully it works for the CRAN version, too (#374)

Fix rmd/CRAN issues

---

R/periods.r

I appear to be just one commit ahead of the master branch on the parent repository.
I'm making a pull request of just the clean up of whitespace in a single file.

cleaned up whitespaces

---

man/Period-class.Rd
man/make_datetime.Rd
man/period.Rd
man/quick_periods.Rd

updated Rd documentation files

---

tests/testthat/test-accessors.R

clean up whitespace

---

R/am-pm.r

Fix small error in am-pm.r documentation

---

NEWS.md
R/guess.r
tests/testthat/test-parsers.R

fixes #411
Parsings seems to work with the code test I posted in the issue.
``` r
Sys.setlocale("LC_TIME", "French_France.1252")
#> [1] "French_France.1252"
vdate <- paste0(format(dmy("13/01/1973") + (0:11)*months(1), "%B"), "131973")
vdate
#>  [1] "janvier131973"   "février131973"   "mars131973"     
#>  [4] "avril131973"     "mai131973"       "juin131973"     
#>  [7] "juillet131973"   "août131973"      "septembre131973"
#> [10] "octobre131973"   "novembre131973"  "décembre131973"
mdy(vdate)
#>  [1] "1973-01-13" "1973-02-13" "1973-03-13" "1973-04-13" "1973-05-13"
#>  [6] "1973-06-13" "1973-07-13" "1973-08-13" "1973-09-13" "1973-10-13"
#> [11] "1973-11-13" "1973-12-13"
mdy(vdate[1])
#> [1] "1973-01-13"
mdy(vdate[2])
#> [1] "1973-02-13"
mdy(vdate[1:2])
#> [1] "1973-01-13" "1973-02-13" …
```

delete extra > in num_exact regex

---

R/parse.r

* For me a noun after 'whenever the guessed' would make more sense

Fix typos in documentation.

---

NEWS.md
R/round.r
tests/testthat/test-round.R

fix ceiling_date return type when unit = "week"

---

R/parse.r

fixed typo

---

.Rbuildignore
.github/move.yml

* Closes #678
* Add move-issues bot configuration file.
* Add \.github to .Rbuildignore

Configure move-issue bot

---

NEWS.md
R/durations.r
R/intervals.r
R/periods.r
man/interval.Rd
tests/testthat/test-durations.R
tests/testthat/test-intervals.R
tests/testthat/test-periods.R

Ensure empty constructors return 0-length vectors

---

R/ops-integer-division.r
R/timespans.r
man/Timespan-class.Rd
tests/testthat/test-ops-integer-division.R
tests/testthat/test-ops-integer-division.txt

Eliminate ambiguous dispatch for %/%

---

R/POSIXt.r
R/parse.r
R/stamp.r
R/util.r

Closes #844 
Any new tests needed?

use is_utc to test UTC input

---

tests/testthat/test-accessors.R
tests/testthat/test-durations.R
tests/testthat/test-ops-addition.R
tests/testthat/test-ops-division.R

updates testthat style in test-accessors.R as per #810 
this issue shouldn't be closed though, because it refers to updating style in 13 different files

update tests to modern style

---

tests/testthat/test-ops-multiplication.R
tests/testthat/test-ops-subtraction.R
tests/testthat/test-periods.R
tests/testthat/test-timespans.R
tests/testthat/test-timezones.R

update more tests to modern style

---

NEWS.md
R/ops-addition.r
tests/testthat/test-ops-addition.R
tests/testthat/test-settors.R

Changing hour, minute or second of Date object now yields POSIXct.

---

R/accessors-tz.r
man/tz.Rd

Polishing tz() docs some more

---

DESCRIPTION

From this commit: https://github.com/tidyverse/lubridate/commit/4c8428b7b3bd30c8789340381ebd9f455308dc27

Bump dev version to reflect TZDIR fix

---

src/utils.c

IINM the variable-size array is vulnerable to stack overflow segfault.

Prefer R_alloc to declaring variable-size array

---

R/round.r
tests/testthat/test-round.R

Remember to use 'as_datetime' in 'round_date'

---

man/DateTimeUpdate.Rd
man/as.duration.Rd
man/as.interval.Rd
man/as.period.Rd
man/as_date.Rd
man/cyclic_encoding.Rd
man/date_decimal.Rd
man/day.Rd
man/decimal_date.Rd
man/fit_to_timeline.Rd
man/force_tz.Rd
man/format_ISO8601.Rd
man/interval.Rd
man/period.Rd
man/round_date.Rd
man/timespan.Rd
man/within-interval.Rd

Followup to #1031, I think we just forgot to redocument after applying styler (which also touches example code)

Redocument

---

README.Rmd

Correcting a typo on README.Rmd

---

DESCRIPTION
NEWS.md

Move timechange from Depends to Imports

---

R/tzdir.R

return early when finding a directory
